name: SimpleLifeSteal
version: '${project.version}'
main: com.simplelifesteal.SimpleLifeSteal
api-version: 1.19
authors: [ the5gi ]
description: A simple Life Steal plugin that doesn't require a config! Add it to your server and instantly have it working :)

commands:
  simplelifesteal:
    description: thingy command
    usage: /simplelifesteal
    permission: sls.sls
  resethearts:
    description: resets a players hearts
    usage: /resethearts player
    permission: sls.admin
  sethearts:
    description: sets a players hearts
    usage: /sethearts player amount
    permission: sls.admin
  givescroll:
    description: gives yourself the scroll you desire
    usage: /givescroll ripped/heart
    permission: sls.admin
  customitem:
    description: gives a custom item coded into the plugin
    usage: /customitem item
    permission: sls.admin
  #reviveplayer:
    #description: Revives a player once they died. Requires the heart item
    #usage: /reviveplayer player
    #permission: sls.revive
  #adminrevive:
    #description: Forces a revive.
    #usage: /adminrevive player
    #permission: sls.admin
  #getdeadplayers:
    #usage: /getdeadplayers
